/**
 * COCHRANE MASTER BUILDERS — Website Discovery Questionnaire
 * 
 * 21-section decision framework for website design and development.
 * All answers resolved through Fantasy.co Brand Identity Architect lens.
 * Referenced by all design, copy, UX, and architecture decisions.
 */

export const DISCOVERY_QUESTIONNAIRE = {
  meta: {
    title: 'Cochrane Master Builders — Website Discovery Questionnaire',
    purpose: 'Structured decision framework for bespoke website design',
    status: 'answered' as const,
  },

  sections: [
    // =========================================================================
    // SECTION 1 — Website Vision and Creative Standard
    // =========================================================================
    {
      id: 'section-1',
      title: 'Website Vision and Creative Standard',
      questions: [
        { id: '1.1', question: 'What should this website feel like within the first 5 seconds of landing on it?', type: 'longText' as const, options: [], answer: "Deeply satisfying and capable — like stepping into a freshly restored home. Not luxury, not cheap, not corporate. Grounded confidence with immediate proof of transformation. The visitor should feel: 'These people do serious work, and they'll come to me.'" },
        { id: '1.2', question: 'Which of these best describes the level of ambition for the website experience?', type: 'multipleChoice' as const, options: ['Basic local service site', 'Clean modern brand site', 'Highly custom premium brand site', 'Fantasy.co-level digital object with bespoke interactions'], answer: 'Fantasy.co-level digital object with bespoke interactions' },
        { id: '1.3', question: 'What do you want someone to immediately understand before they scroll?', type: 'longText' as const, options: [], answer: 'This is residential interior finishing in Calgary — we come to you, we handle the mess, and the before/after results are real. This is not a quick handyman fix.' },
        { id: '1.4', question: 'What should make this website feel different from a typical Calgary builder website?', type: 'longText' as const, options: [], answer: "Every Calgary builder site looks the same: blue gradient, stock addition, 'quality service' headline, cluttered package grid. This site leads with transformation proof, uses real photography exclusively, communicates through the feeling of the reset rather than a feature list, and treats the website itself as a premium object — bespoke motion, editorial restraint, and a narrative arc that builds desire before asking for the booking." },
        { id: '1.5', question: 'Which emotional priorities should the site emphasize most strongly?', type: 'checkboxes' as const, options: ['Relief', 'Pride', 'Fresh-start feeling', 'Convenience', 'Trust', 'Satisfaction', 'Transformation', 'Calm confidence', '"Build it like it is ours" feeling', '"No judgment" reassurance'], answer: ['Relief', 'Satisfaction', 'Transformation', 'Fresh-start feeling', 'Trust', 'Calm confidence', '"Build it like it is ours" feeling', '"No judgment" reassurance'] },
        { id: '1.6', question: 'Which visual priorities matter most for the overall experience?', type: 'checkboxes' as const, options: ['Editorial restraint', 'Tactile material closeups', 'Cinematic atmosphere', 'Strong before/after proof', 'Custom shape language', 'Minimal but premium motion', 'Clear conversion flow', 'Mobile-first design', 'Local Calgary realism', 'Founder-led trust'], answer: ['Strong before/after proof', 'Cinematic atmosphere', 'Tactile material closeups', 'Minimal but premium motion', 'Clear conversion flow', 'Mobile-first design', 'Local Calgary realism', 'Editorial restraint', 'Custom shape language', 'Founder-led trust'] },
        { id: '1.7', question: 'What should the site absolutely never feel like?', type: 'longText' as const, options: [], answer: 'Generic, corporate, franchise-like, over-luxury-coded, cluttered, cheap, salesy, template-driven, blue-gradient quick handyman fix aesthetic, stock-photo dependent, masculine-aggressive, or performatively "premium" without substance.' },
        { id: '1.8', question: 'If the finished site were compared to brands or studios you admire, what kind of reaction would make you feel it succeeded?', type: 'longText' as const, options: [], answer: "'This doesn't look like a quoteing website — it looks like a brand.' 'How is a local mobile builder's site this good?' 'I want to book just because of how the site made me feel.'" },
        { id: '1.9', question: 'What would "Fantasy.co quality" mean for this project in your own words?', type: 'longText' as const, options: [], answer: 'Fantasy.co quality means every interaction is intentional, every section earns its place, the motion is purposeful not decorative, the photography does the heavy lifting, and the whole experience feels like a single cohesive object — not assembled from parts. It means the site could win an Awwwards but more importantly it converts Calgary homeowners who need a reset.' },
      ],
    },

    // =========================================================================
    // SECTION 2 — Brand Expression Through the Website
    // =========================================================================
    {
      id: 'section-2',
      title: 'Brand Expression Through the Website',
      questions: [
        { id: '2.1', question: 'Which brand traits must come through most clearly in the website design and copy?', type: 'checkboxes' as const, options: ['Obsessive', 'Calm', 'Capable', 'Personal', 'Local', 'Crafted', 'Restorative', 'Sensory', 'Premium without arrogance', 'Straightforward', 'Trustworthy', 'Outcome-focused'], answer: ['Capable', 'Restorative', 'Sensory', 'Outcome-focused', 'Straightforward', 'Trustworthy', 'Personal', 'Crafted', 'Premium without arrogance'] },
        { id: '2.2', question: 'Which of these tensions should the site handle most carefully?', type: 'checkboxes' as const, options: ['Premium look without luxury exclusivity', 'Strong transformation without overpromising', 'Direct copy without sounding harsh', 'Emotional copy without sounding cheesy', 'Personal founder brand without feeling too small', 'Affordable/value-led offer with elevated presentation'], answer: ['Premium look without luxury exclusivity', 'Strong transformation without overpromising', 'Emotional copy without sounding cheesy', 'Affordable/value-led offer with elevated presentation', 'Personal founder brand without feeling too small'] },
        { id: '2.3', question: 'How should the website balance premium presentation with accessibility?', type: 'longText' as const, options: [], answer: "The site should feel like a beautifully designed tool that serves real people with real messes. It should look better than anything in the category — but the imagery, copy, and proof should all feature everyday Calgary homes in real condition states. The premium is in the craft of the website and the depth of the restoration, not in the customer's lifestyle. A parent with a fixer-upper should feel just as welcome as someone with a neglected townhome." },
        { id: '2.4', question: 'Which phrases or brand ideas should the site lean into?', type: 'checkboxes' as const, options: ['Build it like it is ours', 'Full reset', 'For homes that have gone too long', 'We come to you', 'Real-life homes', 'Restoration-grade convenience', 'Fresh-start custom home building', 'Serious results for overdue homes', 'Deep clean you can feel', 'Mobile home reset'], answer: ['Build it like it is ours', 'Full reset', 'We come to you', 'Deep clean you can feel', 'Serious results for overdue homes', 'For homes that have gone too long', 'Mobile home reset', 'Fresh-start custom home building'] },
        { id: '2.5', question: 'Which phrases, clichés, or tones should the site avoid?', type: 'longText' as const, options: [], answer: "'Attention to detail,' 'quality service,' 'premium results,' 'customer satisfaction guaranteed,' 'showroom perfection,' 'your home deserves the best,' 'we treat every home like our own,' 'no job too big or too small,' 'trusted by hundreds,' any superlative without proof, any luxury-coded language." },
        { id: '2.6', question: 'How prominently should "no judgment" or "for overdue homes" messaging appear?', type: 'multipleChoice' as const, options: ['Not at all', 'Subtle undertone only', 'Visible in a few key sections', 'A major brand principle throughout the site'], answer: 'Visible in a few key sections' },
        { id: '2.7', question: 'How much should the founder personality show through the website?', type: 'multipleChoice' as const, options: ['Very little', 'Present but understated', 'Strong personal presence', 'Founder-led brand should be very visible'], answer: 'Strong personal presence' },
        { id: '2.8', question: 'What should people remember most about the brand after leaving the site?', type: 'longText' as const, options: [], answer: "That this person does real work, shows real results, comes to you, and doesn't judge the mess. The before/afters were undeniable. And booking felt easy." },
      ],
    },

    // =========================================================================
    // SECTION 3 — Audience Fit and Self-Identification
    // =========================================================================
    {
      id: 'section-3',
      title: 'Audience Fit and Self-Identification',
      questions: [
        { id: '3.1', question: 'Who should immediately feel "this is for me" when they land on the site?', type: 'longText' as const, options: [], answer: "Anyone in Calgary whose home has crossed into problem-state — the busy professional whose townhome hasn't been cleaned in 8 months, the parent whose addition floor is a disaster, the tradesperson whose truck cab is caked in dust, the commuter who's been 'meaning to deal with it.' They should see a before/after that looks like their home and think 'finally, someone who gets it.'" },
        { id: '3.2', question: 'Which customer groups should the website speak to most directly?', type: 'checkboxes' as const, options: ['Busy professionals', 'Parents with family homes', 'Tradespeople / legacy estate owners', 'Commuters', 'Rideshare homeowners', 'People preparing to sell their home', 'People with very neglected interiors', 'General everyday homeowners'], answer: ['Busy professionals', 'Parents with family homes', 'People with very neglected interiors', 'Tradespeople / legacy estate owners', 'People preparing to sell their home', 'Commuters'] },
        { id: '3.3', question: 'Which customer groups should the site not be optimized around right now?', type: 'longText' as const, options: [], answer: 'Luxury/exotic home enthusiasts seeking wall finish or PPF, competition show-prep customers, bargain-only customers who will always choose the cheapest option regardless of result, and weekly-maintenance customers who want regular light washes.' },
        { id: '3.4', question: 'What emotional state is your ideal customer usually in before they book?', type: 'checkboxes' as const, options: ['Embarrassed', 'Annoyed', 'Overwhelmed', 'Tired of putting it off', 'Skeptical', 'Price-sensitive', 'Hopeful for a reset', 'Ready to solve it now', 'Just browsing', 'Comparing providers'], answer: ['Tired of putting it off', 'Overwhelmed', 'Hopeful for a reset', 'Ready to solve it now', 'Embarrassed', 'Comparing providers', 'Price-sensitive'] },
        { id: '3.5', question: 'What should the site say or show so that someone with a very dirty home does not self-exclude?', type: 'longText' as const, options: [], answer: "Show before/after pairs of homes in genuinely bad condition — the worse the starting state, the more dramatic and satisfying the result. Use captions like 'This addition hadn't been cleaned in 14 months. Here's the reset.' Never use language that implies a dirty home is unusual or shameful. Show variety: food buildup, pet hair, work-truck grime, kid mess. The visual message is 'we've seen it all, and this is where we do our best work.'" },
        { id: '3.6', question: 'What should a customer with an average daily-homeowner mess feel when reading the site?', type: 'longText' as const, options: [], answer: "'This is exactly what I need — a proper reset without hassle. And the price is fair.' They should feel like this service is right-sized for them, not overkill." },
        { id: '3.7', question: 'What should a customer with a seriously neglected home feel when reading the site?', type: 'longText' as const, options: [], answer: "'Oh thank god — someone who won't judge me and can actually handle this.' The site should make them feel relief and possibility, not deeper embarrassment." },
        { id: '3.8', question: 'What should a price-aware but quality-seeking visitor feel when reading the site?', type: 'longText' as const, options: [], answer: "'This is clearly a real service with real results, and the price includes travel. This isn't a cheap wipe-down and it isn't a luxury upsell — it's a fair deal for a genuine restoration.'" },
        { id: '3.9', question: 'If someone is comparing you to cheaper mobile cleaners, what should the website make them understand?', type: 'longText' as const, options: [], answer: 'The difference between surface cleaning and deep extraction. Show the extraction bucket — what came OUT of the seats. Show the before/after contrast. The cheaper service moves dirt around. This service removes what\'s embedded and restores how the home feels.' },
        { id: '3.10', question: 'If someone is comparing you to high-end luxury builders, what should the website make them understand?', type: 'longText' as const, options: [], answer: "This isn't trying to be luxury. It's trying to be the most satisfying, most convenient, most honest custom build you can get in Calgary. No showroom pretense. No upsell theater. Just deep extraction, paint restoration, and a home that feels factory-fresh — brought to your door for ~$100." },
      ],
    },

    // =========================================================================
    // SECTION 4 — Website Goals and Success Actions
    // =========================================================================
    {
      id: 'section-4',
      title: 'Website Goals and Success Actions',
      questions: [
        { id: '4.1', question: 'What is the single most important action the website should drive?', type: 'multipleChoice' as const, options: ['Book immediately', 'Request a quote', 'Start a conversation by text', 'Submit inquiry form', 'Call directly', 'View proof first, then inquire'], answer: 'View proof first, then inquire' },
        { id: '4.2', question: 'What secondary actions should the website support?', type: 'checkboxes' as const, options: ['View before/after transformations', 'Compare services', 'Read FAQs', 'Check service area', 'Message on Instagram', 'Call or text', 'Read about Cochrane Master Builders', 'See pricing guidance', 'Ask whether their home is a fit'], answer: ['View before/after transformations', 'See pricing guidance', 'Read FAQs', 'Check service area', 'Call or text', 'Read about Cochrane Master Builders', 'Ask whether their home is a fit'] },
        { id: '4.3', question: 'Which visitor actions should happen above the fold on mobile?', type: 'checkboxes' as const, options: ['Understand the offer', 'See transformation proof', 'Tap Book', 'Tap Text / Call', 'See starting price logic', 'See service area', 'Understand this is mobile', 'Feel reassured this is for dirty homes too'], answer: ['Understand the offer', 'See transformation proof', 'Tap Book', 'Understand this is mobile', 'Tap Text / Call'] },
        { id: '4.4', question: 'What would count as a "high-quality lead" from the website?', type: 'longText' as const, options: [], answer: "Someone in Calgary with a home that needs a real reset — not a quick wash, not a hobby inquiry. They have a home, a timeline, and a willingness to pay ~$100 for a full detail. They understand this is mobile and they're in the Calgary service area." },
        { id: '4.5', question: 'What would count as a "bad-fit lead" that the site should help filter out?', type: 'longText' as const, options: [], answer: 'Someone wanting a $30 express wash, someone outside Calgary, someone wanting services not offered (wall finish, PPF, structural roughing), or someone expecting a full respray or permanent damage repair.' },
        { id: '4.6', question: 'Do you want the site to push more toward instant booking or qualified inquiry?', type: 'multipleChoice' as const, options: ['Strong instant booking', 'Balanced', 'Qualified inquiry first', 'Not sure yet'], answer: 'Balanced' },
        { id: '4.7', question: 'What should the site accomplish for people who are not ready to book today?', type: 'longText' as const, options: [], answer: 'Build trust through proof, create desire through before/afters, make the brand memorable enough that when they ARE ready, Cochrane Master Builders is the first name that comes to mind. Encourage saving/bookmarking through the strength of the content, not through a newsletter pop-up.' },
      ],
    },

    // =========================================================================
    // SECTION 5 — Site Structure and Information Architecture
    // =========================================================================
    {
      id: 'section-5',
      title: 'Site Structure and Information Architecture',
      questions: [
        { id: '5.1', question: 'Which pages should definitely exist in version one of the site?', type: 'checkboxes' as const, options: ['Home', 'Services', 'Results / Transformations', 'About Cochrane Master Builders', 'Service Area', 'Book / Quote', 'FAQ', 'Contact', 'Care Guide / Blog', 'Reviews page', 'Pricing page', 'Case studies page'], answer: ['Home', 'Services', 'Results / Transformations', 'About Cochrane Master Builders', 'Book / Quote', 'FAQ'] },
        { id: '5.2', question: 'If the site had to feel especially intentional and premium, would you rather have:', type: 'multipleChoice' as const, options: ['One long high-conversion page', 'A small multi-page site', 'A hybrid one-page experience with a few deeper supporting pages'], answer: 'A hybrid one-page experience with a few deeper supporting pages' },
        { id: '5.3', question: 'What should the homepage do that no other page needs to do?', type: 'longText' as const, options: [], answer: "Create the complete emotional arc from awareness to desire to action in a single scroll. It must compress proof, offer, trust, and convenience into one cinematic flow that makes someone want to book before they've explored any other page." },
        { id: '5.4', question: 'What should the Services page do that the homepage should not try to fully handle?', type: 'longText' as const, options: [], answer: 'Go deeper into what\'s included, what affects pricing, what to expect during the service, and realistic outcomes by home condition. The homepage sells the feeling; the Services page answers the practical questions.' },
        { id: '5.5', question: 'What should the Results / Transformations page prove?', type: 'longText' as const, options: [], answer: 'That the transformations are real, varied, and dramatic. That homes in genuinely bad condition come out looking and feeling restored. That the proof is undeniable and documented from real Calgary jobs.' },
        { id: '5.6', question: 'What should the About page make people feel about Cochrane Master Builders personally?', type: 'longText' as const, options: [], answer: "That this is a real person with real standards who genuinely cares about the quality of the reset. Not a faceless company. Not a hustler. Someone who takes pride in the craft and won't cut corners." },
        { id: '5.7', question: 'What should the Service Area page accomplish beyond just listing Calgary coverage?', type: 'longText' as const, options: [], answer: 'Reassure Calgary visitors that their specific area is covered, that travel is included, and that the service operates in real neighborhoods — not just downtown. Light neighborhood references add local credibility.' },
        { id: '5.8', question: 'What should the Book / Quote page feel like?', type: 'longText' as const, options: [], answer: "Fast, calm, and reassuring — like a premium app checkout. Minimal fields, clear expectations, no friction. The visitor should feel 'that was easy' not 'that was a form.' Include a text/call alternative for people who prefer direct contact." },
        { id: '5.9', question: 'Are there any pages or sections you already know you do not want?', type: 'longText' as const, options: [], answer: 'No blog/care-guide at launch, no separate reviews page (integrate into Results and homepage), no separate pricing page (integrate into Services and homepage snapshot), no case-studies page (integrate into Results).' },
        { id: '5.10', question: 'What content should be repeated lightly across the site because it is so important?', type: 'checkboxes' as const, options: ['We come to you', 'Calgary-wide mobile service', 'Travel included', 'This is for overdue homes', 'Before/after proof', 'Clear service boundaries', 'Starting pricing logic', 'No-judgment tone', 'Founder trust', 'Easy booking'], answer: ['We come to you', 'Calgary-wide mobile service', 'Travel included', 'Before/after proof', 'No-judgment tone', 'Easy booking', 'Starting pricing logic'] },
      ],
    },

    // =========================================================================
    // SECTION 6 — Homepage Narrative and Section-by-Section Direction
    // =========================================================================
    {
      id: 'section-6',
      title: 'Homepage Narrative and Section-by-Section Direction',
      questions: [
        { id: '6.1', question: 'What is the ideal homepage headline territory?', type: 'multipleChoice' as const, options: ['Emotional first', 'Outcome first', 'Convenience first', 'Transformation first', 'Hybrid of emotional + explanatory'], answer: 'Hybrid of emotional + explanatory' },
        { id: '6.2', question: 'Which headline direction feels strongest right now?', type: 'dropdown' as const, options: ['Build it like it is ours', 'A custom build, brought to you', 'Custom home building for homes that need a custom build', 'Restore the feel of a clean home again', 'For homes that have gone too long', 'Custom headline not listed'], answer: 'Build it like it is ours' },
        { id: '6.3', question: 'If you want a custom headline not listed above, what should it be trying to express?', type: 'longText' as const, options: [], answer: 'N/A — selected headline works.' },
        { id: '6.4', question: 'What should the hero subhead clarify without becoming too long?', type: 'longText' as const, options: [], answer: 'Mobile home restoration across Calgary. Deep interior extraction. Paint restoration. Travel included. From ~$100.' },
        { id: '6.5', question: 'What should the first primary CTA say?', type: 'shortText' as const, options: [], answer: 'Book Your Reset' },
        { id: '6.6', question: 'What should the secondary CTA say?', type: 'shortText' as const, options: [], answer: 'See Transformations' },
        { id: '6.7', question: 'What trust line or support line should appear near the hero?', type: 'longText' as const, options: [], answer: 'Mobile in Calgary · Travel Included · Full Detail from ~$100 · No Judgment' },
        { id: '6.8', question: 'What should appear immediately after the hero?', type: 'multipleChoice' as const, options: ['Before/after slider', 'Service overview', 'Social proof', 'Quick pricing snapshot', 'How it works', 'Mixed proof block'], answer: 'Before/after slider' },
        { id: '6.9', question: 'What should the "immediate proof" section include?', type: 'checkboxes' as const, options: ['Before/after slider', 'Close-up restoration tiles', 'Short captions', 'Problem-state labels', 'Outcome-state labels', 'Interior focus', 'Exterior focus', 'Condition categories', 'Mini case studies'], answer: ['Before/after slider', 'Close-up restoration tiles', 'Short captions', 'Problem-state labels', 'Outcome-state labels', 'Interior focus', 'Condition categories'] },
        { id: '6.10', question: 'What should the homepage communicate before it ever gets into process details?', type: 'longText' as const, options: [], answer: 'That the results are real, the service comes to you, and this is for homes in real condition — not showroom homes. The emotional hook and visual proof must land before any process explanation.' },
        { id: '6.11', question: 'What sections should definitely appear on the homepage?', type: 'checkboxes' as const, options: ['Hero', 'Immediate proof', 'Outcome-led service overview', 'How it works', 'Why Cochrane Master Builders', 'Pricing snapshot', 'Service area', 'Testimonials', 'FAQ preview', 'Final CTA', 'Founder section', 'Transformation gallery preview'], answer: ['Hero', 'Immediate proof', 'Outcome-led service overview', 'How it works', 'Pricing snapshot', 'Testimonials', 'FAQ preview', 'Final CTA', 'Founder section'] },
        { id: '6.12', question: 'What should the order of homepage sections be if you were optimizing for conversion and emotional impact?', type: 'longText' as const, options: [], answer: 'Hero (emotional hook + CTA) → Immediate proof (before/after slider) → Outcome-led service overview (what you get, not how we do it) → How it works (3-step simplicity) → Pricing snapshot (transparency) → Founder section (trust) → Testimonials (social proof) → FAQ preview (objection handling) → Final CTA (emotional close)' },
        { id: '6.13', question: 'Which homepage sections deserve the most design attention and visual richness?', type: 'checkboxes' as const, options: ['Hero', 'Proof section', 'Service outcomes', 'How it works', 'About Cochrane Master Builders', 'Pricing', 'Service area', 'Testimonials', 'FAQ', 'Final CTA'], answer: ['Hero', 'Proof section', 'Final CTA', 'Service outcomes', 'About Cochrane Master Builders'] },
        { id: '6.14', question: 'What should the final CTA section make someone feel right before they act?', type: 'longText' as const, options: [], answer: "Convinced, relieved, and ready. The feeling of 'I've seen enough — this is the right person, the right service, and I'm done putting this off.' The final CTA should feel like a permission to finally act." },
        { id: '6.15', question: 'What "what if" homepage ideas would you want explored before design is finalized?', type: 'longText' as const, options: [], answer: 'What if the hero used a slow before/after crossfade instead of a static image? What if proof came before any text explanation? What if the final CTA section used a single powerful before/after with sensory copy about the feeling of sitting in the restored home?' },
      ],
    },

    // =========================================================================
    // SECTION 7 — Services Page Content Strategy
    // =========================================================================
    {
      id: 'section-7',
      title: 'Services Page Content Strategy',
      questions: [
        { id: '7.1', question: 'How should services be organized on the website?', type: 'multipleChoice' as const, options: ['One flagship full-detail offer', '2–3 simple packages', 'Packages by home condition', 'Interior / exterior / add-ons separated', 'Not sure yet'], answer: 'One flagship full-detail offer' },
        { id: '7.2', question: 'What should each service block clearly explain?', type: 'checkboxes' as const, options: ['Who it is for', 'What problem it solves', 'What is included', 'What result it delivers', 'How long it takes', 'What affects price', 'What is not included', 'Best fit by home condition'], answer: ['What problem it solves', 'What is included', 'What result it delivers', 'What affects price', 'Best fit by home condition', 'Who it is for'] },
        { id: '7.3', question: 'What service naming style feels right?', type: 'multipleChoice' as const, options: ['Plain and descriptive', 'Premium but restrained', 'Emotional / outcome-led', 'Practical with subtle polish'], answer: 'Practical with subtle polish' },
        { id: '7.4', question: 'What should the flagship service ideally be called on the site?', type: 'shortText' as const, options: [], answer: 'The Custom Build' },
        { id: '7.5', question: 'How should interior work be described in customer-friendly language?', type: 'longText' as const, options: [], answer: 'A deep interior reset — stains extracted, buildup removed, odor eliminated, and every surface restored to a fresh, factory-like standard. Not a wipe-down. A reset you can feel the moment you sit down.' },
        { id: '7.6', question: 'How should exterior work be described in customer-friendly language?', type: 'longText' as const, options: [], answer: 'Paint restoration that brings back the finish your home started with — site-finish blemishes reduced, grime removed, and a clean, even surface that catches light the way it used to.' },
        { id: '7.7', question: 'How much process detail should the Services page include?', type: 'multipleChoice' as const, options: ['Very little', 'Enough to reassure people', 'A balanced amount', 'A detailed breakdown'], answer: 'Enough to reassure people' },
        { id: '7.8', question: 'What should be the balance between outcome language and technical detail?', type: 'longText' as const, options: [], answer: "80% outcome language, 20% process detail. The process details exist to make the outcomes believable — 'deep extraction removes embedded grime' makes 'factory-fresh interior' credible. Never lead with process." },
        { id: '7.9', question: 'What service boundaries or expectations should the site clarify to reduce hesitation or disappointment?', type: 'longText' as const, options: [], answer: 'This is restoration, not repair — deep scratches, permanent stains, and structural damage are beyond scope. Home condition affects final pricing. Results vary by starting condition, but the before/after proof shows what\'s realistic.' },
        { id: '7.10', question: 'What are the biggest service-related questions visitors are likely to have?', type: 'longText' as const, options: [], answer: "'What exactly is included?' 'How long does it take?' 'What if my home is really, really dirty?' 'Do I need to provide anything — water, power, space?' 'Interior only, or exterior too?' 'What's the actual price for my home?'" },
        { id: '7.11', question: 'What "what if" service architecture ideas should be explored?', type: 'longText' as const, options: [], answer: "What if the services page framed everything by problem-state rather than service tier? E.g., 'Daily homeowner that needs a refresh' vs 'Home that hasn't been touched in a year' vs 'Work truck with heavy-use buildup.' Each maps to the same core service but with different outcome expectations and pricing guidance." },
      ],
    },

    // =========================================================================
    // SECTION 8 — Results, Proof, and Transformation Storytelling
    // =========================================================================
    {
      id: 'section-8',
      title: 'Results, Proof, and Transformation Storytelling',
      questions: [
        { id: '8.1', question: 'How central should before/after proof be to the website?', type: 'multipleChoice' as const, options: ['Helpful but secondary', 'Very important', 'One of the main conversion homeowners', 'The core proof system of the site'], answer: 'The core proof system of the site' },
        { id: '8.2', question: 'What kinds of transformations should be shown first?', type: 'checkboxes' as const, options: ['Neglected interiors', 'Family homes', 'Work trucks', 'Daily-homeowner townhomes', 'additions', 'Pet hair cleanup', 'Stain removal', 'Exterior revival', 'Pre-sale refreshes'], answer: ['Neglected interiors', 'Family homes', 'Work trucks', 'Daily-homeowner townhomes', 'Stain removal', 'Exterior revival'] },
        { id: '8.3', question: 'How should project cards or transformation entries be structured?', type: 'checkboxes' as const, options: ['Problem state', 'Home type', 'What was done', 'Time taken', 'Outcome description', 'Customer feeling / quote', 'Photos only', 'Condition level'], answer: ['Problem state', 'Home type', 'What was done', 'Outcome description', 'Customer feeling / quote', 'Condition level'] },
        { id: '8.4', question: 'What should a visitor think when they view the Results page?', type: 'longText' as const, options: [], answer: "'If my home looks anything like that before, it could look like that after. These results are real.' The page should make visitors self-identify and feel hopeful." },
        { id: '8.5', question: 'What should the proof feel like visually?', type: 'multipleChoice' as const, options: ['Clinical and straightforward', 'Premium portfolio-like', 'Highly editorial', 'Practical but elevated', 'Evidence-first with subtle art direction'], answer: 'Evidence-first with subtle art direction' },
        { id: '8.6', question: 'What proof assets do you already have, or expect to have, for the site?', type: 'checkboxes' as const, options: ['Before/after photo pairs', 'Close-up material shots', 'Short vertical videos', 'Founder-at-work photos', 'Customer testimonials', 'Home type variety', 'No strong proof assets yet'], answer: ['Before/after photo pairs', 'Close-up material shots', 'Customer testimonials', 'Founder-at-work photos'] },
        { id: '8.7', question: 'What proof is absolutely required before the site can feel credible?', type: 'longText' as const, options: [], answer: 'At minimum 6-8 strong before/after pairs showing variety in home type and condition severity. At least 3 interior extraction close-ups. At least 3 customer quotes with specific outcome language.' },
        { id: '8.8', question: 'How should captions under before/after content be written?', type: 'multipleChoice' as const, options: ['Minimal and understated', 'Practical and descriptive', 'Emotional and satisfying', 'A blend of practical + emotional'], answer: 'A blend of practical + emotional' },
        { id: '8.9', question: 'What should the site show so visitors believe "this is for homes like mine"?', type: 'longText' as const, options: [], answer: "Show a range of home and project types and conditions — townhomes, additions, trucks, starter homes. Show conditions from 'moderately neglected' to 'seriously overdue.' Label each with relatable condition descriptions: 'hadn't been cleaned in a year,' 'two kids, one dog, zero time,' 'legacy estate, daily abuse.'" },
        { id: '8.10', question: 'What "what if" proof ideas should be explored?', type: 'longText' as const, options: [], answer: "Annotated before/after sliders with callout labels ('embedded grime,' 'extraction result,' 'restored finish'). Condition-level filters ('moderate,' 'heavy,' 'severe'). A 'homes like yours' matching section based on home type." },
      ],
    },

    // =========================================================================
    // SECTION 9 — Copywriting Direction and Messaging Hierarchy
    // =========================================================================
    {
      id: 'section-9',
      title: 'Copywriting Direction and Messaging Hierarchy',
      questions: [
        { id: '9.1', question: 'Which messaging order feels right for the website?', type: 'multipleChoice' as const, options: ['Feeling → Result → Evidence → Action', 'Result → Evidence → Feeling → Action', 'Convenience → Result → Proof → Action', 'Proof → Offer → Trust → Action'], answer: 'Feeling → Result → Evidence → Action' },
        { id: '9.2', question: 'Which tone should the site feel closest to?', type: 'checkboxes' as const, options: ['Plainspoken but elevated', 'Composed, not shouty', 'Sensory, not technical-first', 'Trustworthy, not salesy', 'Direct, not over-luxury-coded', 'Warm without being soft', 'Confident without hype'], answer: ['Plainspoken but elevated', 'Sensory, not technical-first', 'Trustworthy, not salesy', 'Direct, not over-luxury-coded', 'Confident without hype', 'Warm without being soft'] },
        { id: '9.3', question: 'How emotional should the copy be overall?', type: 'multipleChoice' as const, options: ['Mostly practical', 'Balanced', 'Emotion-led but restrained', 'Highly emotional and cinematic'], answer: 'Emotion-led but restrained' },
        { id: '9.4', question: 'How direct should the site be about the pain state of a dirty or neglected home?', type: 'multipleChoice' as const, options: ['Very subtle', 'Moderately clear', 'Direct but humane', 'Very explicit'], answer: 'Direct but humane' },
        { id: '9.5', question: 'Which emotional outcomes should the copy emphasize most?', type: 'checkboxes' as const, options: ['Relief', 'Pride', 'Freshness', 'Control', 'Satisfaction', 'Confidence', 'Comfort', 'Resale readiness', 'Less embarrassment', 'Enjoying the home again'], answer: ['Relief', 'Satisfaction', 'Freshness', 'Pride', 'Enjoying the home again', 'Less embarrassment'] },
        { id: '9.6', question: 'Which words or phrases should the site own consistently?', type: 'longText' as const, options: [], answer: 'reset, restore, factory-feel, build it like it is ours, custom build, deep extraction, brought to you, the reveal, mobile restoration, fresh start' },
        { id: '9.7', question: 'Which words or phrases should never appear on the site?', type: 'longText' as const, options: [], answer: 'attention to detail, quality service, premium experience, customer satisfaction, world-class, unmatched, bespoke, luxury, elite, simple clean, just a wash, cheap, budget, we pride ourselves' },
        { id: '9.8', question: 'What should the copy sound like on the homepage versus service pages versus the booking flow?', type: 'longText' as const, options: [], answer: 'Homepage: emotional, cinematic, proof-driven — the copy creates desire. Services page: practical, clear, reassuring — the copy answers questions. Booking flow: minimal, warm, directional — the copy removes friction.' },
        { id: '9.9', question: 'How strongly should the site lean into "we come to you" as copy rather than just an info point?', type: 'multipleChoice' as const, options: ['Mention only where needed', 'Important supporting point', 'Repeated brand promise', 'One of the main lines of the site'], answer: 'Repeated brand promise' },
        { id: '9.10', question: 'How should the site talk about "factory-fresh" or "like-new" outcomes without overclaiming?', type: 'longText' as const, options: [], answer: "Use 'factory-feel' rather than 'factory-new' — it describes the sensory experience without claiming the home is literally new. Support with specific proof: 'the interior your home had when you drove it off the lot.' Let before/afters do the proving." },
        { id: '9.11', question: 'What objections should the copy answer before a visitor has to ask them?', type: 'checkboxes' as const, options: ['Will they judge how bad it is?', 'Can they handle really dirty homes?', 'Is this worth the money?', 'What does the price include?', 'Will booking be annoying?', 'Do they cover my area?', 'How long does it take?', 'Do I need water, power, or space?', 'Is this just a basic clean?', 'Why choose this over another builder?'], answer: ['Will they judge how bad it is?', 'Can they handle really dirty homes?', 'Is this worth the money?', 'What does the price include?', 'Do they cover my area?', 'Is this just a basic clean?', 'Do I need water, power, or space?'] },
        { id: '9.12', question: 'What "what if" copy directions should be explored before final writing begins?', type: 'longText' as const, options: [], answer: "What if the hero copy was purely sensory — describing the FEELING of sitting in a restored home? What if key sections used one-line fragment copy for punch ('Months of neglect. One reset. Done.') rather than paragraphs?" },
      ],
    },

    // =========================================================================
    // SECTION 10 — Visual Identity on the Website
    // =========================================================================
    {
      id: 'section-10',
      title: 'Visual Identity on the Website',
      questions: [
        { id: '10.1', question: 'Which color direction feels most right for the website right now?', type: 'multipleChoice' as const, options: ['Dark and atmospheric', 'Balanced dark/light editorial', 'Lighter premium with darker accents', 'Mostly neutral with restrained accent colors'], answer: 'Balanced dark/light editorial' },
        { id: '10.2', question: 'Which palette directions feel strongest?', type: 'checkboxes' as const, options: ['Asphalt Black', 'Stone Gray', 'Warm Porcelain', 'Petrol Slate', 'Burnished Copper', 'Muted aluminum tones', 'Deep pine-black tones'], answer: ['Asphalt Black', 'Stone Gray', 'Warm Porcelain', 'Burnished Copper'] },
        { id: '10.3', question: 'What should the color system communicate emotionally?', type: 'longText' as const, options: [], answer: 'Grounded, tactile, automotive-adjacent but not cliché. The palette should feel like materials: asphalt, warm stone, clean porcelain, burnished metal. Not corporate. Not luxury. Real and physical.' },
        { id: '10.4', question: 'What should the website avoid in its color styling?', type: 'longText' as const, options: [], answer: 'Black-and-gold luxury coding, bright contractor-blue, harsh red racing accents, all-dark heaviness without relief, pastel softness, neon energy-drink colors, rainbow/multi-color, marble textures.' },
        { id: '10.5', question: 'What kind of shape language should the site use?', type: 'checkboxes' as const, options: ['Precision corners', 'Softened radii', 'Clipped angles', 'Elongated horizontal panels', 'Inset content windows', 'Selective asymmetry', 'Layered overlaps', 'Clean rectangular structure'], answer: ['Precision corners', 'Elongated horizontal panels', 'Inset content windows', 'Clean rectangular structure', 'Selective asymmetry'] },
        { id: '10.6', question: 'How distinctive should the shape system be?', type: 'multipleChoice' as const, options: ['Very subtle', 'Noticeable but restrained', 'A signature part of the identity', 'One of the key differentiators of the site'], answer: 'A signature part of the identity' },
        { id: '10.7', question: 'What should typography do emotionally for the brand?', type: 'longText' as const, options: [], answer: "Create calm confidence. Typography should feel sturdy and clean — never delicate, never aggressive. It should communicate 'we know what we're doing' through weight, spacing, and restraint." },
        { id: '10.8', question: 'Which typography balance feels right?', type: 'multipleChoice' as const, options: ['Mostly clean sans', 'Elegant display + practical sans', 'Editorial serif-heavy', 'Industrial premium sans-led'], answer: 'Industrial premium sans-led' },
        { id: '10.9', question: 'What should the photography style prioritize?', type: 'checkboxes' as const, options: ['Close-up textures', 'Interior atmosphere', 'Paint reflections', 'Natural light', 'Calgary realism', 'Before/after proof', 'Founder presence', 'No generic shiny-home glamour shots', 'Evidence over decoration'], answer: ['Close-up textures', 'Before/after proof', 'Interior atmosphere', 'Calgary realism', 'Natural light', 'Founder presence', 'No generic shiny-home glamour shots', 'Evidence over decoration'] },
        { id: '10.10', question: 'What visual clichés should be completely avoided?', type: 'longText' as const, options: [], answer: 'Spinning home GIFs, water-droplet-on-hood stock photos, generic man-wiping-home-with-cloth imagery, sparkle/shine particle effects, checkered racing patterns, glossy black backgrounds with lens flares, any stock photography of pristine showroom homes.' },
        { id: '10.11', question: 'What "what if" art-direction ideas should be explored?', type: 'longText' as const, options: [], answer: 'Macro texture photography of restored surfaces (leather grain, carpet fibers, paint clarity). Atmospheric interior shots that feel almost architectural. A light-sweep animation in the hero that mimics a paint-correction reveal. Scroll-triggered before/after transitions that feel like wiping away the grime.' },
      ],
    },

    // =========================================================================
    // SECTION 11 — UX Principles and Interaction Design
    // =========================================================================
    {
      id: 'section-11',
      title: 'UX Principles and Interaction Design',
      questions: [
        { id: '11.1', question: 'What should the UX feel like overall?', type: 'checkboxes' as const, options: ['Calm', 'Guided', 'Fast', 'App-like', 'Premium', 'Uncluttered', 'Trustworthy', 'Intentional', 'Easy for stressed users', 'Minimal friction'], answer: ['Calm', 'Guided', 'Premium', 'Uncluttered', 'Trustworthy', 'Intentional', 'Easy for stressed users', 'Minimal friction', 'Fast'] },
        { id: '11.2', question: 'What should the navigation feel like?', type: 'multipleChoice' as const, options: ['Extremely simple and minimal', 'Refined and editorial', 'Utility-first', 'Balanced premium + practical'], answer: 'Balanced premium + practical' },
        { id: '11.3', question: 'What should visitors be able to do with very little effort on mobile?', type: 'checkboxes' as const, options: ['Understand the offer', 'Tap Book', 'Tap Call/Text', 'See proof', 'Check service area', 'Read price guidance', 'Open FAQs', 'See whether their home is a fit'], answer: ['Understand the offer', 'Tap Book', 'Tap Call/Text', 'See proof', 'Read price guidance', 'See whether their home is a fit'] },
        { id: '11.4', question: 'What kind of booking/contact UX would feel most appropriate?', type: 'multipleChoice' as const, options: ['Single simple form', 'Short multi-step form', 'Form + direct text option', 'Primarily text / call with lightweight form support'], answer: 'Form + direct text option' },
        { id: '11.5', question: 'What should happen when someone clicks Book from the homepage?', type: 'longText' as const, options: [], answer: 'A calm, focused booking screen with minimal fields: location, home type, condition level, preferred date. A text/call alternative is always visible. Confirmation is instant and warm. No multi-page wizard. No account creation.' },
        { id: '11.6', question: 'How important is a sticky CTA on mobile?', type: 'multipleChoice' as const, options: ['Not needed', 'Nice to have', 'Important', 'Essential'], answer: 'Essential' },
        { id: '11.7', question: 'How much motion should the site use?', type: 'multipleChoice' as const, options: ['Almost none', 'Subtle throughout', 'Moderate and intentional', 'High-end bespoke motion moments'], answer: 'Moderate and intentional' },
        { id: '11.8', question: 'Which motion ideas feel appropriate?', type: 'checkboxes' as const, options: ['Subtle text reveals', 'Parallax depth', 'Light sweep in hero', 'Smooth section transitions', 'Before/after interaction animation', 'Map motion', 'Refined hover masks', 'Booking transition choreography'], answer: ['Subtle text reveals', 'Before/after interaction animation', 'Smooth section transitions', 'Light sweep in hero', 'Refined hover masks', 'Booking transition choreography'] },
        { id: '11.9', question: 'Which interaction patterns should feel especially refined?', type: 'checkboxes' as const, options: ['Buttons', 'Image sliders', 'Navigation transitions', 'Accordion FAQs', 'Form fields', 'Cards / tiles', 'Hover states', 'Loading / page transitions'], answer: ['Buttons', 'Image sliders', 'Navigation transitions', 'Form fields', 'Hover states', 'Loading / page transitions'] },
        { id: '11.10', question: 'What UX patterns should the site avoid because they would feel too generic, gimmicky, or annoying?', type: 'longText' as const, options: [], answer: 'Auto-playing video backgrounds, chat widgets, cookie banner theatrics, scroll-jacking, infinite scroll galleries, pop-ups of any kind, floating social icons, progress bars that don\'t represent real loading, hamburger menus that animate for 2 seconds.' },
        { id: '11.11', question: 'What "what if" UX ideas should be explored?', type: 'longText' as const, options: [], answer: "What if the before/after slider used a 'wipe' gesture that felt like physically cleaning the surface? What if the booking flow had a home-condition selector with visual examples? What if page transitions used a subtle dark-to-light sweep representing the before/after transformation?" },
      ],
    },

    // =========================================================================
    // SECTION 12 — Mobile-First Design Decisions
    // =========================================================================
    {
      id: 'section-12',
      title: 'Mobile-First Design Decisions',
      questions: [
        { id: '12.1', question: 'How much of your traffic do you expect will arrive from mobile?', type: 'multipleChoice' as const, options: ['Mostly desktop', 'Balanced', 'Mostly mobile', 'Almost entirely mobile'], answer: 'Almost entirely mobile' },
        { id: '12.2', question: 'What must be visible without much scrolling on mobile?', type: 'checkboxes' as const, options: ['Clear headline', 'What the service is', 'That it is mobile', 'CTA to book', 'Proof image or transformation cue', 'Price guidance', 'Service area cue', 'No-judgment reassurance'], answer: ['Clear headline', 'What the service is', 'That it is mobile', 'CTA to book', 'Proof image or transformation cue', 'Price guidance'] },
        { id: '12.3', question: 'How compressed should the mobile homepage feel?', type: 'multipleChoice' as const, options: ['Very concise', 'Balanced', 'Rich but controlled', 'As immersive as desktop, just optimized for thumb flow'], answer: 'Rich but controlled' },
        { id: '12.4', question: 'Which mobile-specific features feel most valuable?', type: 'checkboxes' as const, options: ['Sticky CTA bar', 'Tap-to-call', 'Tap-to-text', 'Condensed proof slider', 'Expandable FAQs', 'Quick quote shortcut', 'Minimal nav', 'Fast load priorities'], answer: ['Sticky CTA bar', 'Tap-to-call', 'Tap-to-text', 'Condensed proof slider', 'Expandable FAQs', 'Minimal nav', 'Fast load priorities'] },
        { id: '12.5', question: 'What should the mobile booking flow optimize for most?', type: 'multipleChoice' as const, options: ['Speed', 'Lead quality', 'Reassurance', 'Simplicity', 'A balance of all four'], answer: 'A balance of all four' },
        { id: '12.6', question: 'What would make the site feel premium on mobile rather than like a generic responsive template?', type: 'longText' as const, options: [], answer: "Custom typography scale for mobile, intentional spacing that doesn't just collapse from desktop, touch-optimized before/after sliders, a sticky CTA bar with bespoke styling, image loading that prioritizes proof content, and micro-interactions on buttons that feel tactile." },
        { id: '12.7', question: 'What "what if" mobile ideas should be explored?', type: 'longText' as const, options: [], answer: "What if the mobile hero was a single before/after with a swipe interaction and the headline overlaid? What if the sticky bar alternated between 'Book Your Reset' and 'Text Cochrane Master Builders' based on scroll position?" },
      ],
    },

    // =========================================================================
    // SECTION 13 — Trust, Reassurance, and Credibility Content
    // =========================================================================
    {
      id: 'section-13',
      title: 'Trust, Reassurance, and Credibility Content',
      questions: [
        { id: '13.1', question: 'What trust signals should appear early in the experience?', type: 'checkboxes' as const, options: ['Founder presence', 'Before/after results', 'Calgary mobile coverage', 'Travel included', 'Starting price clarity', 'Testimonials', 'Clear service inclusions', 'Easy contact options', 'Home-fit reassurance', 'No-judgment language'], answer: ['Before/after results', 'Calgary mobile coverage', 'Travel included', 'Starting price clarity', 'Easy contact options', 'No-judgment language', 'Founder presence'] },
        { id: '13.2', question: 'What should make someone believe you are real, capable, and worth contacting?', type: 'longText' as const, options: [], answer: "Real before/after photography of real Calgary homes. A founder with a name, face, and visible standard. Specific customer quotes describing outcomes. Transparent pricing with travel included. A professional website that demonstrates more care than any competitor in the category." },
        { id: '13.3', question: 'How prominently should reviews/testimonials appear?', type: 'multipleChoice' as const, options: ['Light support only', 'Important but restrained', 'A major trust block', 'Not sure yet'], answer: 'Important but restrained' },
        { id: '13.4', question: 'What kind of testimonials would be most persuasive on the site?', type: 'checkboxes' as const, options: ['Relief after the service', 'Visible transformation', 'Convenience of mobile service', 'No judgment / easy process', 'Worth the money', 'Specific condition improvement', 'Fast and professional experience'], answer: ['Relief after the service', 'Visible transformation', 'Convenience of mobile service', 'No judgment / easy process', 'Worth the money', 'Specific condition improvement'] },
        { id: '13.5', question: 'How much should the site explain logistics like water, power, access, and timing?', type: 'multipleChoice' as const, options: ['Only in FAQ', 'Visible in one supporting section', 'Clearly addressed in multiple places', 'Very important to reduce friction early'], answer: 'Clearly addressed in multiple places' },
        { id: '13.6', question: 'What trust content should the site use besides reviews?', type: 'checkboxes' as const, options: ['Clear pricing logic', 'Honest service boundaries', 'Founder standards / philosophy', 'Transformation case studies', 'Home condition examples', 'Process transparency', 'Service area clarity'], answer: ['Clear pricing logic', 'Honest service boundaries', 'Founder standards / philosophy', 'Transformation case studies', 'Process transparency', 'Service area clarity'] },
        { id: '13.7', question: 'What fears should the trust system reduce most strongly?', type: 'checkboxes' as const, options: ['Being judged', 'Getting upsold unexpectedly', 'Wasting money on a light clean', 'Booking hassle', 'Not being in the service area', 'Not knowing what to expect', 'Thinking the home is too far gone'], answer: ['Being judged', 'Wasting money on a light clean', 'Thinking the home is too far gone', 'Not knowing what to expect', 'Getting upsold unexpectedly'] },
        { id: '13.8', question: 'What "what if" trust content should be explored?', type: 'longText' as const, options: [], answer: "A 'Cochrane Master Builders's Standard' section — a short founder-voice block stating what every home gets and what 'done' means. A 'homes like yours' visual grid showing common home and project types and conditions. Realistic expectation notes under proof content." },
      ],
    },

    // =========================================================================
    // SECTION 14 — Pricing and Offer Clarity on the Site
    // =========================================================================
    {
      id: 'section-14',
      title: 'Pricing and Offer Clarity on the Site',
      questions: [
        { id: '14.1', question: 'How visible should pricing be on the website?', type: 'multipleChoice' as const, options: ['Hidden until inquiry', 'Starting price only', 'Clear starting price plus explanation', 'Detailed pricing structure'], answer: 'Clear starting price plus explanation' },
        { id: '14.2', question: 'How should the site frame the current "about $100" reference?', type: 'multipleChoice' as const, options: ['As a starting point', 'As an average detail', 'As a simple from-price', 'Do not mention until clarified'], answer: 'As a starting point' },
        { id: '14.3', question: 'What pricing questions does the website need to answer clearly?', type: 'longText' as const, options: [], answer: "'What does ~$100 include?' 'Does home size matter?' 'What if my home is in really bad shape — does that cost more?' 'Are there add-ons?' 'Is travel really included?'" },
        { id: '14.4', question: 'Which pricing-related reassurance should the site provide?', type: 'checkboxes' as const, options: ['Travel included', 'Straightforward pricing logic', 'Condition may affect final cost', 'No hidden surprises', 'Clear inclusions', 'Worth-it framing through outcomes', 'Easy quote path'], answer: ['Travel included', 'Straightforward pricing logic', 'Condition may affect final cost', 'No hidden surprises', 'Clear inclusions', 'Worth-it framing through outcomes', 'Easy quote path'] },
        { id: '14.5', question: 'What should the visitor feel when they encounter pricing on the site?', type: 'longText' as const, options: [], answer: "Informed, relieved, and confident the price is fair. Not suspicious, not trapped, not confused. The reaction should be 'that's straightforward and reasonable for what I'm getting.'" },
        { id: '14.6', question: 'What should the site not do when presenting pricing?', type: 'longText' as const, options: [], answer: "Feel vague, feel like a bait-and-switch, require a form submission to reveal, use 'call for pricing' as the primary path, present a complex tier grid, or use defensive language about pricing." },
        { id: '14.7', question: 'What "what if" pricing presentation ideas should be explored?', type: 'longText' as const, options: [], answer: "What if pricing were presented as a single 'starting from' figure with a visual explainer showing what affects the final number (home size, condition level)? A simple visual scale, not a spreadsheet." },
      ],
    },

    // =========================================================================
    // SECTION 15 — Founder Story and About Content
    // =========================================================================
    {
      id: 'section-15',
      title: 'Founder Story and About Content',
      questions: [
        { id: '15.1', question: 'How personal should the About Cochrane Master Builders content be?', type: 'multipleChoice' as const, options: ['Mostly professional', 'Balanced personal and professional', 'Strong personal story', 'Very founder-led brand narrative'], answer: 'Strong personal story' },
        { id: '15.2', question: 'What should people learn about Cochrane Master Builders that helps the website convert better?', type: 'longText' as const, options: [], answer: "His standards — what 'done' means to him. Why he started — the satisfaction of transforming a neglected home. Why mobile — because convenience should be real, not an afterthought. That he personally does every detail — this isn't a franchise, it's craftsmanship." },
        { id: '15.3', question: 'What should the founder story avoid?', type: 'longText' as const, options: [], answer: "Being too long, sounding like a LinkedIn bio, inventing mythology, trying to be inspirational, reading like a résumé, or positioning him as a 'visionary.' It should sound like Cochrane Master Builders talking to you in your driveway." },
        { id: '15.4', question: 'What kind of founder photography should the site use?', type: 'checkboxes' as const, options: ['At work', 'Environmental portraits', 'With home closeups', 'Minimal headshots only', 'Local Calgary context', 'Hands/detail moments', 'Tool/process moments used sparingly'], answer: ['At work', 'Environmental portraits', 'With home closeups', 'Local Calgary context', 'Hands/detail moments'] },
        { id: '15.5', question: 'What should the About page make a skeptical visitor feel?', type: 'longText' as const, options: [], answer: "'This is a real guy who clearly gives a damn about the work.' The About page should convert skeptics through authenticity, not persuasion." },
        { id: '15.6', question: 'What "what if" About-page ideas should be explored?', type: 'longText' as const, options: [], answer: 'What if the About section was a short manifesto — 3-4 sentences about what Cochrane Master Builders believes, why he does this, and what his standard is? Not a biography. A declaration of craft.' },
      ],
    },

    // =========================================================================
    // SECTION 16 — Calgary Locality and Service Area Content
    // =========================================================================
    {
      id: 'section-16',
      title: 'Calgary Locality and Service Area Content',
      questions: [
        { id: '16.1', question: 'How important is Calgary-local identity to the website?', type: 'multipleChoice' as const, options: ['Minor detail', 'Useful trust signal', 'Important differentiator', 'Core part of the brand feel'], answer: 'Important differentiator' },
        { id: '16.2', question: 'What should the site communicate about service area beyond "Calgary-wide"?', type: 'longText' as const, options: [], answer: 'That travel is included everywhere in Calgary. That this is a local, founder-operated service — not a franchise. That Cochrane Master Builders knows the city and operates across all quadrants.' },
        { id: '16.3', question: 'Should neighborhoods, zones, or common areas be named on the website?', type: 'yesNo' as const, options: ['Yes', 'No'], answer: 'Yes' },
        { id: '16.4', question: 'What should the Service Area page or section feel like?', type: 'multipleChoice' as const, options: ['Purely practical', 'Practical with premium design', 'Strong local-brand statement', 'Mostly utility with light trust-building'], answer: 'Practical with premium design' },
        { id: '16.5', question: 'What local visual cues would feel authentic rather than forced?', type: 'longText' as const, options: [], answer: 'Real before/after photos taken in recognizable Calgary residential contexts — driveways, suburban streets, parking lots. Weather-appropriate imagery. No forced skyline shots or tourism imagery.' },
        { id: '16.6', question: 'What "what if" local-content ideas should be explored?', type: 'longText' as const, options: [], answer: "What if the service area used a minimal, stylized Calgary map with a subtle pulse animation showing coverage — not a Google Maps embed but a custom, branded illustration?" },
      ],
    },

    // =========================================================================
    // SECTION 17 — FAQ and Objection Handling
    // =========================================================================
    {
      id: 'section-17',
      title: 'FAQ and Objection Handling',
      questions: [
        { id: '17.1', question: 'Which FAQs are essential for launch?', type: 'checkboxes' as const, options: ['Can you handle really dirty homes?', 'What does the detail include?', 'How much does it cost?', 'Do you come to me anywhere in Calgary?', 'How long does it take?', 'Do I need to provide water or power?', 'Is this interior only or interior + exterior?', 'What homes are a good fit?', 'How do I book?', 'Can you help with stains, smells, pet hair, or buildup?'], answer: ['Can you handle really dirty homes?', 'What does the detail include?', 'How much does it cost?', 'Do you come to me anywhere in Calgary?', 'How long does it take?', 'Do I need to provide water or power?', 'Is this interior only or interior + exterior?', 'Can you help with stains, smells, pet hair, or buildup?', 'How do I book?'] },
        { id: '17.2', question: 'Which objections should the FAQ answer most clearly?', type: 'checkboxes' as const, options: ['My home is too far gone', "I'm worried about being judged", "I'm unsure whether it's worth it", 'I need more clarity on price', "I don't know how mobile service works", "I don't know whether my area is covered", "I'm comparing other builders", 'I need to understand expectations'], answer: ['My home is too far gone', "I'm worried about being judged", "I'm unsure whether it's worth it", 'I need more clarity on price', "I don't know how mobile service works", 'I need to understand expectations'] },
        { id: '17.3', question: 'What tone should FAQ answers use?', type: 'multipleChoice' as const, options: ['Very brief and direct', 'Practical and reassuring', 'Friendly and explanatory', 'Premium and editorial', 'Plainspoken with calm reassurance'], answer: 'Plainspoken with calm reassurance' },
        { id: '17.4', question: 'What questions do you wish people would stop asking because the website should answer them upfront?', type: 'longText' as const, options: [], answer: "'Do you come to my area?' and 'Is the price all-inclusive?' — both should be answered clearly before anyone reaches the FAQ." },
        { id: '17.5', question: 'What "what if" FAQ ideas should be explored?', type: 'longText' as const, options: [], answer: "What if the FAQ opened with a 'Your home isn't too dirty' reassurance note before the accordion? What if condition-level questions were answered with before/after thumbnails inline?" },
      ],
    },

    // =========================================================================
    // SECTION 18 — Calls to Action and Conversion Language
    // =========================================================================
    {
      id: 'section-18',
      title: 'Calls to Action and Conversion Language',
      questions: [
        { id: '18.1', question: 'What should the main CTA language feel like?', type: 'multipleChoice' as const, options: ['Practical and direct', 'Emotional and outcome-led', 'Premium and understated', 'Hybrid of direct + outcome-led'], answer: 'Hybrid of direct + outcome-led' },
        { id: '18.2', question: 'Which CTA direction feels strongest?', type: 'checkboxes' as const, options: ['Book a Detail', 'Get a Quote', 'Get My Home Back', 'Start My Reset', 'View Transformations', 'Check Availability', 'See If Your Home Is a Fit', 'Text to Book'], answer: ['Book a Detail', 'Get My Home Back', 'Start My Reset', 'View Transformations', 'Text to Book'] },
        { id: '18.3', question: 'What should the CTA never sound like?', type: 'longText' as const, options: [], answer: "Aggressive, cheap, gimmicky ('ACT NOW!'), overly corporate ('Submit Inquiry'), passive ('Learn More'), or cute ('Give Your Home a Spa Day')." },
        { id: '18.4', question: 'Where should CTAs appear most strategically?', type: 'checkboxes' as const, options: ['Hero', 'After proof', 'After services overview', 'After pricing snapshot', 'Within Results page', 'Sticky mobile bar', 'Final CTA section', 'Nav'], answer: ['Hero', 'After proof', 'After pricing snapshot', 'Sticky mobile bar', 'Final CTA section', 'Nav'] },
        { id: '18.5', question: 'What should happen emotionally each time a CTA appears?', type: 'longText' as const, options: [], answer: "A micro-wave of confidence and relief — 'I've seen enough, this is what I need, and this button makes it easy.' Each CTA placement should follow a moment of proof or reassurance that has just resolved a hesitation." },
        { id: '18.6', question: 'What "what if" CTA ideas should be explored?', type: 'longText' as const, options: [], answer: "What if the final CTA used a before/after background with the line 'Your home is next' rather than a generic booking prompt?" },
      ],
    },

    // =========================================================================
    // SECTION 19 — Content Assets Needed for the Website
    // =========================================================================
    {
      id: 'section-19',
      title: 'Content Assets Needed for the Website',
      questions: [
        { id: '19.1', question: 'Which content assets are already available or likely to be available?', type: 'checkboxes' as const, options: ['Logo / wordmark', 'Brand colors', 'Before/after images', 'Close-up texture photography', 'Founder portraits', 'Customer testimonials', 'Service descriptions', 'Pricing guidance', 'Calgary area quotes', 'Short video clips', 'No strong assets yet'], answer: ['Before/after images', 'Service descriptions', 'Pricing guidance', 'Calgary area quotes'] },
        { id: '19.2', question: 'Which assets are most important to create before design goes too far?', type: 'checkboxes' as const, options: ['Hero photography/video', 'Before/after portfolio', 'Founder photos', 'Service inclusion copy', 'Pricing framework', 'FAQ answers', 'Neighborhood/service-area copy', 'Testimonial collection', 'Proof captions / case studies'], answer: ['Before/after portfolio', 'Founder photos', 'Hero photography/video', 'Testimonial collection', 'Service inclusion copy', 'Pricing framework'] },
        { id: '19.3', question: 'What content gaps would weaken the site the most if they are not solved early?', type: 'longText' as const, options: [], answer: 'Before/after photography — without strong proof pairs, the entire trust system collapses. The site cannot launch without at least 6-8 documented transformations.' },
        { id: '19.4', question: 'What visual assets would make the site feel truly custom rather than template-driven?', type: 'longText' as const, options: [], answer: "Real before/after photography from Calgary jobs, founder-at-work documentary photography, close-up extraction and material shots, and a custom wordmark/logo if one doesn't exist yet." },
        { id: '19.5', question: 'What written content assets would make the site feel deeply convincing?', type: 'longText' as const, options: [], answer: 'Specific customer testimonials with outcome language, a founder manifesto/standards statement, and FAQ answers that feel like a real person answering honestly.' },
      ],
    },

    // =========================================================================
    // SECTION 20 — Signature Moments and "What If" Exploration
    // =========================================================================
    {
      id: 'section-20',
      title: 'Signature Moments and "What If" Exploration',
      questions: [
        { id: '20.1', question: 'Which bespoke moments are worth exploring for this site?', type: 'checkboxes' as const, options: ['Hero light-sweep reveal', 'Annotated before/after slider', 'Minimal Calgary motion map', 'Editorial "factory-feel" sensory section', 'Elevated booking transition', 'Material-based hover masks', 'Scroll-timed storytelling moments', 'Problem-state to reset-state section transitions'], answer: ['Annotated before/after slider', 'Hero light-sweep reveal', 'Scroll-timed storytelling moments', 'Problem-state to reset-state section transitions', 'Elevated booking transition', 'Editorial "factory-feel" sensory section'] },
        { id: '20.2', question: 'Which of these should be a true signature moment, not just a nice detail?', type: 'longText' as const, options: [], answer: "The before/after slider must be the true signature interaction — a bespoke, tactile, drag-to-reveal experience with annotated callouts that feels unlike any other builder site's generic gallery. This is the moment that proves the brand." },
        { id: '20.3', question: 'What if the homepage led with proof before a long explanation—would that feel stronger or weaker for this brand?', type: 'longText' as const, options: [], answer: 'Stronger. Proof before explanation builds instant credibility in a category full of empty claims. The before/after slider immediately after the hero headline eliminates skepticism and earns the right to tell the rest of the story.' },
        { id: '20.4', question: 'What if the site used a much more editorial visual rhythm with larger photography and less copy—would that help or hurt trust?', type: 'longText' as const, options: [], answer: 'Help trust — IF the photography is strong and real. Large proof photography carries more conviction than paragraphs of copy. The editorial rhythm should be photography-led with supporting text, not the reverse.' },
        { id: '20.5', question: 'What if the site framed the offer as one powerful "custom build" instead of several services—would that clarify the brand or oversimplify it?', type: 'longText' as const, options: [], answer: "Clarify the brand. One 'Custom Build' offer is cleaner, more memorable, and truer to how the service actually works. Condition-based pricing notes handle variation without fragmenting the offer." },
        { id: '20.6', question: 'What if "for homes that have gone too long" became a central section or recurring line—would that help self-identification or feel too narrow?', type: 'longText' as const, options: [], answer: 'Help self-identification — used as a recurring support line rather than a headline. It\'s a powerful qualifier that makes the right customer lean in. As a section title or recurring phrase, it sharpens targeting without alienating lighter-need customers.' },
        { id: '20.7', question: 'What if the site became darker and more cinematic—would that feel premium or too luxury-coded?', type: 'longText' as const, options: [], answer: 'A balanced dark/light editorial approach is better than full dark. A darker hero with lighter content sections creates rhythm and prevents the luxury-coded feeling. Full dark risks feeling like a luxury builder targeting Lamborghini owners.' },
        { id: '20.8', question: 'What if the site used more warm light surfaces and editorial whitespace—would that feel more accessible or less automotive?', type: 'longText' as const, options: [], answer: "More accessible — warm light surfaces with editorial whitespace feel approachable and premium simultaneously. This is the right territory for a brand that serves 'normal people with real messes.' The automotive association comes from the photography, not the color scheme." },
        { id: '20.9', question: 'What if the booking experience felt almost like a premium app—would that match the brand or feel excessive for the current business stage?', type: 'longText' as const, options: [], answer: "Match the brand at a controlled level. A clean, focused booking moment with minimal friction and warm confirmation feels elevated without being excessive. No account creation, no multi-page wizard — just enough polish to signal 'this person takes their business seriously.'" },
        { id: '20.10', question: 'What if we made the founder more visible throughout the site—would that increase trust or make the brand feel too small?', type: 'longText' as const, options: [], answer: "Increase trust significantly. At this business stage, the founder IS the brand. Showing Cochrane Master Builders at work, referencing his standards, and putting his name behind the promise makes the brand feel more trustworthy, not smaller. The site's design quality prevents it from feeling amateur." },
        { id: '20.11', question: 'What if pricing were stated very clearly and early—would that increase trust or reduce inquiries from people who need more context first?', type: 'longText' as const, options: [], answer: "Increase trust. In this price range and category, price transparency signals honesty and reduces the 'call for a quote' friction that kills conversion. People who need more context can still inquire, but most will appreciate knowing the starting point immediately." },
        { id: '20.12', question: 'What if testimonials were minimal and the proof system carried most of the trust load—would that feel stronger for this category?', type: 'longText' as const, options: [], answer: 'Stronger. In residential finishing, the visual proof system (before/after) is inherently more convincing than written testimonials. 3-4 strong testimonials integrated into the flow is sufficient. The transformations carry the trust load.' },
        { id: '20.13', question: 'What if the site explicitly reassured people with very messy homes—would that convert better or risk sounding too negative?', type: 'longText' as const, options: [], answer: "Convert better — dramatically. The biggest barrier for the ideal customer is embarrassment and self-exclusion. Explicit reassurance ('we've seen it all, no judgment') directly addresses the #1 emotional blocker. Frame it as possibility, not negativity." },
        { id: '20.14', question: 'What if the site leaned more rugged and practical than editorial and premium—would that improve fit for real-life homeowners or reduce perceived quality?', type: 'longText' as const, options: [], answer: 'Reduce perceived quality. The website\'s design quality is what separates Cochrane Master Builders from every other local builder. A rugged/practical aesthetic would blend into the category. The editorial premium approach — applied to real, grounded content — is the strategic advantage.' },
        { id: '20.15', question: 'What if the site leaned more premium and restrained than practical and direct—would that create stronger desire or risk self-exclusion?', type: 'longText' as const, options: [], answer: "Create stronger desire without self-exclusion, IF the content stays grounded. Premium restraint in design + real-life proof imagery + accessible pricing = the sweet spot. The visitor thinks 'this looks better than anything else in the category, AND it's for regular homes like mine.'" },
        { id: '20.16', question: 'What if there were a dedicated "Is your home a fit?" section or micro-flow—would that reduce bad leads and boost confidence?', type: 'longText' as const, options: [], answer: "Reduce bad leads and boost confidence. A simple 'Is your home a fit?' section with home-type icons and condition-level descriptions would help visitors self-qualify while reinforcing that all conditions are welcome." },
        { id: '20.17', question: 'What if the Results page were treated like a curated portfolio rather than a simple gallery—would that make the transformation feel more valuable?', type: 'longText' as const, options: [], answer: "Make the transformation feel significantly more valuable. A curated portfolio with condition tags, home and project types, and outcome descriptions elevates the proof from 'photo dump' to 'documented craftsmanship.' This is one of the highest-impact page decisions." },
        { id: '20.18', question: 'What if the copy became more sensory and less explanatory in some key sections—would that deepen desire or weaken clarity?', type: 'longText' as const, options: [], answer: "Deepen desire in the hero and final CTA sections specifically. Sensory copy ('the smell of a home that's been reset — clean fabric, fresh air, no trace of what was there before') creates visceral desire. Use sensory in bookend sections, practical in the middle." },
        { id: '20.19', question: 'What if there were one section focused purely on the feeling after the detail—smell, atmosphere, pride, freshness, relief—would that feel powerful or too abstract?', type: 'longText' as const, options: [], answer: "Powerful — this is a signature brand moment. A short section dedicated to 'The Feeling After' — describing the sensory reset (smell, sight, touch, pride) — would be unlike anything in the category and would tap directly into the emotional homeowner of the purchase. Keep it to 3-4 lines with atmospheric photography." },
        { id: '20.20', question: 'What is the one bold website idea you would most want explored before final direction is chosen?', type: 'longText' as const, options: [], answer: 'The before/after slider as a full-width, edge-to-edge hero interaction — where the headline IS the before/after, and dragging the slider reveals both the transformation and the brand promise simultaneously. The first thing you do on the site is reveal a reset.' },
      ],
    },

    // =========================================================================
    // SECTION 21 — Final Alignment and Decision Filters
    // =========================================================================
    {
      id: 'section-21',
      title: 'Final Alignment and Decision Filters',
      questions: [
        { id: '21.1', question: 'When reviewing homepage concepts, what should be the top decision criteria?', type: 'checkboxes' as const, options: ['Feels bespoke', 'Converts clearly', 'Explains mobile value', 'Shows transformation fast', 'Feels local and real', 'Welcomes overdue homes', 'Avoids cliché home-builder branding', 'Feels premium without arrogance', 'Supports easy booking', 'Feels memorable'], answer: ['Feels bespoke', 'Converts clearly', 'Shows transformation fast', 'Feels local and real', 'Welcomes overdue homes', 'Avoids cliché home-builder branding', 'Feels premium without arrogance', 'Supports easy booking', 'Feels memorable'] },
        { id: '21.2', question: 'When reviewing copy concepts, what should be the top decision criteria?', type: 'checkboxes' as const, options: ['Sounds human', 'Sounds specific', 'Answers objections', 'Feels emotionally resonant', 'Avoids generic service language', 'Avoids judgment', 'Uses the right level of confidence', 'Feels believable', 'Supports action'], answer: ['Sounds human', 'Sounds specific', 'Answers objections', 'Feels emotionally resonant', 'Avoids generic service language', 'Avoids judgment', 'Feels believable', 'Supports action'] },
        { id: '21.3', question: 'When reviewing UI concepts, what should be the top decision criteria?', type: 'checkboxes' as const, options: ['Mobile-first', 'Easy to navigate', 'Visually distinctive', 'Proof-forward', 'Calm and uncluttered', 'Elegant interactions', 'Strong CTA placement', 'Fast-feeling', 'Trust-building'], answer: ['Mobile-first', 'Proof-forward', 'Calm and uncluttered', 'Strong CTA placement', 'Visually distinctive', 'Trust-building', 'Fast-feeling', 'Easy to navigate'] },
        { id: '21.4', question: 'What would make you reject a concept immediately, even if it looks polished?', type: 'longText' as const, options: [], answer: "If it looks like it could be any builder's website. If it uses stock photography. If the copy contains 'quality service' or 'attention to detail.' If the pricing is hidden. If it feels luxury-coded. If a parent with a fixer-upper would feel out of place." },
        { id: '21.5', question: 'What would make you say "this is exactly it" when reviewing an early website direction?', type: 'longText' as const, options: [], answer: "When the before/after slider makes me want to book a quote for my own home. When the copy sounds like a real person, not a brochure. When the whole experience feels like one cohesive object — not assembled from sections. When I forget I'm looking at a local service website." },
        { id: '21.6', question: 'If this website is exceptionally successful, what will people feel, understand, and do differently because of it?', type: 'longText' as const, options: [], answer: 'They will feel that getting their home properly finished is easier, more accessible, and more satisfying than they expected. They will understand that Cochrane Master Builders is not a quick handyman fix — it\'s a residential finishing and home-building service that comes to them and handles the whole thing. And they will book, or save the site to book when they\'re ready, because the proof was undeniable and the experience was memorable.' },
      ],
    },
  ],
} as const;
