/**
 * meta-config.ts — Per-route <head> metadata for Cochrane Tile Masters.
 *
 * Generated by: Per-Trade SEO Copy System (Prompt 2)
 * Trade: tile | Brand: Cochrane Tile Masters | Primary: Cochrane
 *
 * DO NOT EDIT manually after generation — use the SEO Copy System to
 * regenerate for a new trade. Area pages (/areas-we-serve/*) manage
 * their own meta dynamically via communities.ts.
 *
 * Title rule: ≤ 60 chars. Primary keyword + city first. Brand name last.
 * Desc rule:  140–155 chars. Keyword + city + outcome + trust signal.
 *             No price mentions. Ends with "Send photos for a quote."
 */

export interface PageMeta {
  /** ≤ 60 chars. Rendered in <title> and as fallback for ogTitle. */
  title: string;
  /** 140–155 chars. No exclamation marks. No banned words. */
  description: string;
  /** ≤ 70 chars. Can be more editorial than SEO title. Falls back to title. */
  ogTitle?: string;
  /** Falls back to description. */
  ogDescription?: string;
  /**
   * Absolute canonical URL. Replace CANONICAL_ORIGIN at deploy time.
   * e.g. https://cochranetile.ca
   */
  canonical?: string;
}

// ─── Origin placeholder — replace at build time or in env ────────────────────
const ORIGIN = "https://cochrane-master-builders.com";

// ─── Static route map ─────────────────────────────────────────────────────────
export const META_CONFIG: Record<string, PageMeta> = {

  "/": {
    title: "Tile Installation Cochrane | Cochrane Tile Masters",
    // 151 chars
    description:
      "Tile installation in Cochrane — floors, showers, and backsplash. Written scope, 15-year structural guarantee on every invoice. Send photos for a quote.",
    ogTitle: "Cochrane Tile Masters — The Tile Stays.",
    canonical: `${ORIGIN}/`,
  },

  "/brand-story": {
    title: "Our Story | Cochrane Tile Masters",
    // 146 chars
    description:
      "The craft behind Cochrane Tile Masters. Why we dry-lay every floor, measure lippage on every install, and have done this in Cochrane for 26 years.",
    ogTitle: "Why We Dry-Lay Every Floor — The Cochrane Tile Masters Story",
    canonical: `${ORIGIN}/brand-story`,
  },

  "/why-we-love": {
    title: "Why We Love Tile | Cochrane Tile Masters",
    // 149 chars
    description:
      "An honest account of what tile installation actually demands — lippage, dry layouts, mortar coverage. Written by people who measure grout joints off the clock.",
    ogTitle: "Why We Love Tile. An Honest Confession.",
    canonical: `${ORIGIN}/why-we-love`,
  },

  "/services": {
    title: "Tile Services Cochrane | Cochrane Tile Masters",
    // 148 chars
    description:
      "Floor tile, shower surrounds, large-format, backsplash, and tile repair in Cochrane. Every install to TCNA standard. 15-year structural guarantee. Send photos.",
    ogTitle: "Every Tile Service Cochrane Needs — One Crew.",
    canonical: `${ORIGIN}/services`,
  },

  "/pricing": {
    title: "Tile Installation Pricing | Cochrane Tile Masters",
    // 153 chars
    description:
      "Tile pricing in Cochrane: written ranges by scope, substrate, and format — before work starts, not after. No surprise invoices. Send photos for a quote.",
    ogTitle: "Tile Pricing in Cochrane — Written Before Work Starts.",
    canonical: `${ORIGIN}/pricing`,
  },

  "/gallery": {
    title: "Tile Work Gallery Cochrane | Cochrane Tile Masters",
    // 150 chars
    description:
      "Floor tile, shower surrounds, and backsplash work in Cochrane and Rocky View County. Before-and-after photography from completed projects. 15-year guarantee.",
    ogTitle: "Tile Work in Cochrane — Before and After.",
    canonical: `${ORIGIN}/gallery`,
  },

  "/reviews": {
    title: "Tile Installation Reviews | Cochrane Tile Masters",
    // 152 chars
    description:
      "What Cochrane homeowners say after floor tile, shower, and backsplash installations. Specific outcomes, timelines, and written guarantee references.",
    ogTitle: "What Cochrane Homeowners Say — In Their Words.",
    canonical: `${ORIGIN}/reviews`,
  },

  "/about": {
    title: "About Cochrane Tile Masters",
    // 154 chars
    description:
      "Cochrane Tile Masters builds as the seventh generation in a town shaped by builders since 1881. TCNA standard, $5M liability coverage, 15-year guarantee.",
    ogTitle: "About Cochrane Tile Masters — The Seventh Generation.",
    canonical: `${ORIGIN}/about`,
  },

  "/contact": {
    title: "Contact Cochrane Tile Masters",
    // 148 chars
    description:
      "Send 2–3 photos of the space and one sentence about the project. Written range back within one business day. No call required to start. Cochrane and area.",
    ogTitle: "Start With Two Photos — Cochrane Tile Masters.",
    canonical: `${ORIGIN}/contact`,
  },

  "/thank-you": {
    title: "Request Received | Cochrane Tile Masters",
    // 145 chars
    description:
      "Your project photos are in. We review every submission and reply with a written range within one business day. No call required unless you prefer it.",
    ogTitle: "Request Received — Cochrane Tile Masters",
    canonical: `${ORIGIN}/thank-you`,
  },

  "/guarantee": {
    title: "Tile Installation Guarantee | Cochrane Tile Masters",
    description:
      "The Generational Finish Guarantee: clean worksite or work is free, 14-day zero-cost touch-up, 15-year structural warranty. In writing on every invoice. Send photos for a quote.",
    ogTitle: "Three Guarantees. Every Project. In Writing.",
    canonical: `${ORIGIN}/guarantee`,
  },

  "/faq": {
    title: "Tile Installation FAQ | Cochrane Tile Masters",
    description:
      "Answers to the most common tile installation questions — pricing, process, timeline, guarantees, and service areas. Written quotes within 24 hours. Send photos for a quote.",
    ogTitle: "Tile Installation FAQ — Cochrane Tile Masters.",
    canonical: `${ORIGIN}/faq`,
  },

  "/privacy": {
    title: "Privacy Policy | Cochrane Tile Masters",
    // 140 chars
    description:
      "How Cochrane Tile Masters collects, uses, and protects the information you share when requesting a project quote or using this website.",
    canonical: `${ORIGIN}/privacy`,
  },

  "/terms": {
    title: "Terms of Service | Cochrane Tile Masters",
    // 143 chars
    description:
      "Terms governing use of the Cochrane Tile Masters website, project quote requests, and service agreements for tile installation in Cochrane, AB.",
    canonical: `${ORIGIN}/terms`,
  },
};

// ─── Dynamic service detail meta ─────────────────────────────────────────────
/**
 * Generates PageMeta for /services/:slug routes.
 * slug is the URL-safe sub-service identifier from SubService.slug
 * (e.g. "floor-tile", "shower-tiling", "large-format-tile").
 */
export const META_SERVICE_DETAIL = (slug: string): PageMeta => {
  const labelMap: Record<string, { keyword: string; outcome: string }> = {
    "floor-tile": {
      keyword: "Floor Tile Installation Cochrane",
      outcome:
        "mortar-bed floor tile for kitchens, bathrooms, and entryways. Written scope, TCNA standard, 15-year guarantee. Send photos for a quote.",
    },
    "shower-tiling": {
      keyword: "Shower Tile Installation Cochrane",
      outcome:
        "shower surrounds and wet room floors with waterproofing membrane. No moisture failures. 15-year structural guarantee. Send photos for a quote.",
    },
    "backsplash": {
      keyword: "Backsplash Tile Cochrane",
      outcome:
        "kitchen and bathroom backsplash in subway, mosaic, or large-format. Cut flush to cabinetry and outlets. Written scope. Send photos for a quote.",
    },
    "large-format-tile": {
      keyword: "Large-Format Tile Installation Cochrane",
      outcome:
        "24×24 and 32×32 porcelain with lippage control and full mortar coverage. TCNA standard, 15-year guarantee. Send photos for a quote.",
    },
    "tile-repair": {
      keyword: "Tile Repair Cochrane",
      outcome:
        "cracked, hollow, and lifted tile removal and reset — matched to existing grout. Written scope, 15-year guarantee. Send photos for a quote.",
    },
  };

  const entry = labelMap[slug];
  if (!entry) {
    return {
      title: `Tile Services | Cochrane Tile Masters`,
      description:
        "Tile installation and repair in Cochrane, AB. Written scope, TCNA standard, 15-year structural guarantee on every invoice. Send photos for a quote.",
      canonical: `${ORIGIN}/services/${slug}`,
    };
  }

  const title = `${entry.keyword} | Cochrane Tile Masters`.slice(0, 60);
  const description = `${entry.keyword} — ${entry.outcome}`.slice(0, 155);

  return {
    title,
    description,
    canonical: `${ORIGIN}/services/${slug}`,
  };
};
