/**
 * why-we-love-copy.ts — Trade-specific manifesto content for /why-we-love.
 *
 * Generated by: Per-Trade SEO Copy System (Prompt 2)
 * Trade: tile | Brand: Cochrane Tile Masters
 *
 * All {SERVICE} tokens resolved. No template placeholders remain.
 * Written as the third-generation master of this trade — not a marketer.
 *
 * DO NOT modify template-copy.ts. This file provides the resolved version
 * of TEMPLATE_COPY.whyWeLove for this specific trade.
 */

export interface WhyWeLoveCopy {
  /** The "1mm no one else cares about" opening statement. */
  obsessionHeadline: string;
  /** 2–3 sentences on the trade-specific tolerance the obsession lives in. */
  obsessionBody: string;
  /** Exactly 3 objects: Material, Method, Measurement. Order is fixed. */
  methods: [
    { title: "Material"; body: string },
    { title: "Method";   body: string },
    { title: "Measurement"; body: string },
  ];
  /** The house-rule manifesto statement. The line that goes on the wall. */
  quote: string;
  heroEyebrow: string;
  heroTitle: string;
  heroLede: string;
}

export const WHY_WE_LOVE_COPY: WhyWeLoveCopy = {

  obsessionHeadline: "The lippage no one measures until the floor is grouted.",

  obsessionBody:
    "Lippage is the height difference between the edges of adjacent tiles. ANSI A108.02 allows up to 1/32 inch for tiles under 15 inches in any dimension. Most installers treat that number as the target. We treat it as the maximum. We carry a calibrated lippage gauge on every floor installation and record the reading in the project notes — not because it changes the invoice, but because it tells us whether the floor is right.",

  methods: [
    {
      title: "Material",
      body: "Porcelain, ceramic, and natural stone behave differently under mortar, temperature cycling, and substrate movement. Porcelain is near-impermeable — it requires higher trowel notch coverage and full back-buttering on tiles over 15 inches. Natural stone varies by quarry cut and absorption rate. A 24×24 porcelain tile distributes point load differently than a 12×12 ceramic. We specify mortar type, trowel geometry, and back-butter requirement before any tile leaves the box. That decision is made from the substrate up, not from the catalogue down.",
    },
    {
      title: "Method",
      body: "The dry layout is four hours of work that sets no tile permanently. We snap chalk lines, lay the full field dry, find the optical centre of the room — which is rarely the geometric centre, because rooms in residential construction are rarely square — and determine every cut tile before mortar is mixed. Sixty percent of tile installations that read wrong were wrong before the first tile was set. The dry layout is where we catch it. We have never skipped it. We have been mocked for this. The floors have not been wrong.",
    },
    {
      title: "Measurement",
      body: "Grout joint width is not aesthetic preference. It is a tolerance band governed by tile format and local thermal cycle. Most residential tile is produced with a manufacturing variance of ±1mm per tile. A 2mm grout joint absorbs that variance without compression cracking. A 1.5mm joint does not survive a Cochrane winter — the freeze-thaw cycle produces lateral force the joint cannot accommodate. We set joint width by tile format and climate, then hold it with calibrated spacers to ±0.3mm across the field. This is not perfectionism. It is the difference between a floor that lasts and one that does not.",
    },
  ],

  quote:
    "The floor your grandchildren walk on was set the day we refused to skip the dry layout.",

  heroEyebrow: "An honest confession from people who measure grout joints off the clock",

  heroTitle: "Why We Love Tile",

  heroLede:
    "We have measured grout joints in other people's bathrooms at social events and said nothing. Out loud. This is the explanation.",
};
